<?php

//add_filter('vc_iconpicker_render_filter', function(){});
add_filter('vc_iconpicker-type-ionicons', function ($icons) {
	$ionicons = array(
		'Common'  => array(
			array('ion-alert' => 'alert'),
			array('ion-alert-circled' => 'alert-circled'),
			array('ion-aperture' => 'aperture'),
			array('ion-archive' => 'archive'),
			array('ion-arrow-down-a' => 'arrow-down-a'),
			array('ion-arrow-down-b' => 'arrow-down-b'),
			array('ion-arrow-down-c' => 'arrow-down-c'),
			array('ion-arrow-expand' => 'arrow-expand'),
			array('ion-arrow-graph-down-left' => 'arrow-graph-down-left'),
			array('ion-arrow-graph-down-right' => 'arrow-graph-down-right'),
			array('ion-arrow-graph-up-left' => 'arrow-graph-up-left'),
			array('ion-arrow-graph-up-right' => 'arrow-graph-up-right'),
			array('ion-arrow-left-a' => 'arrow-left-a'),
			array('ion-arrow-left-b' => 'arrow-left-b'),
			array('ion-arrow-left-c' => 'arrow-left-c'),
			array('ion-arrow-move' => 'arrow-move'),
			array('ion-arrow-resize' => 'arrow-resize'),
			array('ion-arrow-return-left' => 'arrow-return-left'),
			array('ion-arrow-return-right' => 'arrow-return-right'),
			array('ion-arrow-right-a' => 'arrow-right-a'),
			array('ion-arrow-right-b' => 'arrow-right-b'),
			array('ion-arrow-right-c' => 'arrow-right-c'),
			array('ion-arrow-shrink' => 'arrow-shrink'),
			array('ion-arrow-swap' => 'arrow-swap'),
			array('ion-arrow-up-a' => 'arrow-up-a'),
			array('ion-arrow-up-b' => 'arrow-up-b'),
			array('ion-arrow-up-c' => 'arrow-up-c'),
			array('ion-asterisk' => 'asterisk'),
			array('ion-at' => 'at'),
			array('ion-backspace' => 'backspace'),
			array('ion-backspace-outline' => 'backspace-outline'),
			array('ion-bag' => 'bag'),
			array('ion-battery-charging' => 'battery-charging'),
			array('ion-battery-empty' => 'battery-empty'),
			array('ion-battery-full' => 'battery-full'),
			array('ion-battery-half' => 'battery-half'),
			array('ion-battery-low' => 'battery-low'),
			array('ion-beaker' => 'beaker'),
			array('ion-beer' => 'beer'),
			array('ion-bluetooth' => 'bluetooth'),
			array('ion-bonfire' => 'bonfire'),
			array('ion-bookmark' => 'bookmark'),
			array('ion-bowtie' => 'bowtie'),
			array('ion-briefcase' => 'briefcase'),
			array('ion-bug' => 'bug'),
			array('ion-calculator' => 'calculator'),
			array('ion-calendar' => 'calendar'),
			array('ion-camera' => 'camera'),
			array('ion-card' => 'card'),
			array('ion-cash' => 'cash'),
			array('ion-chatbox' => 'chatbox'),
			array('ion-chatbox-working' => 'chatbox-working'),
			array('ion-chatboxes' => 'chatboxes'),
			array('ion-chatbubble' => 'chatbubble'),
			array('ion-chatbubble-working' => 'chatbubble-working'),
			array('ion-chatbubbles' => 'chatbubbles'),
			array('ion-checkmark' => 'checkmark'),
			array('ion-checkmark-circled' => 'checkmark-circled'),
			array('ion-checkmark-round' => 'checkmark-round'),
			array('ion-chevron-down' => 'chevron-down'),
			array('ion-chevron-left' => 'chevron-left'),
			array('ion-chevron-right' => 'chevron-right'),
			array('ion-chevron-up' => 'chevron-up'),
			array('ion-clipboard' => 'clipboard'),
			array('ion-clock' => 'clock'),
			array('ion-close' => 'close'),
			array('ion-close-circled' => 'close-circled'),
			array('ion-close-round' => 'close-round'),
			array('ion-closed-captioning' => 'closed-captioning'),
			array('ion-cloud' => 'cloud'),
			array('ion-code' => 'code'),
			array('ion-code-download' => 'code-download'),
			array('ion-code-working' => 'code-working'),
			array('ion-coffee' => 'coffee'),
			array('ion-compass' => 'compass'),
			array('ion-compose' => 'compose'),
			array('ion-connection-bars' => 'connection-bars'),
			array('ion-contrast' => 'contrast'),
			array('ion-crop' => 'crop'),
			array('ion-cube' => 'cube'),
			array('ion-disc' => 'disc'),
			array('ion-document' => 'document'),
			array('ion-document-text' => 'document-text'),
			array('ion-drag' => 'drag'),
			array('ion-earth' => 'earth'),
			array('ion-easel' => 'easel'),
			array('ion-edit' => 'edit'),
			array('ion-egg' => 'egg'),
			array('ion-eject' => 'eject'),
			array('ion-email' => 'email'),
			array('ion-email-unread' => 'email-unread'),
			array('ion-erlenmeyer-flask' => 'erlenmeyer-flask'),
			array('ion-erlenmeyer-flask-bubbles' => 'erlenmeyer-flask-bubbles'),
			array('ion-eye' => 'eye'),
			array('ion-eye-disabled' => 'eye-disabled'),
			array('ion-female' => 'female'),
			array('ion-filing' => 'filing'),
			array('ion-film-marker' => 'film-marker'),
			array('ion-fireball' => 'fireball'),
			array('ion-flag' => 'flag'),
			array('ion-flame' => 'flame'),
			array('ion-flash' => 'flash'),
			array('ion-flash-off' => 'flash-off'),
			array('ion-folder' => 'folder'),
			array('ion-fork' => 'fork'),
			array('ion-fork-repo' => 'fork-repo'),
			array('ion-forward' => 'forward'),
			array('ion-funnel' => 'funnel'),
			array('ion-gear-a' => 'gear-a'),
			array('ion-gear-b' => 'gear-b'),
			array('ion-grid' => 'grid'),
			array('ion-hammer' => 'hammer'),
			array('ion-happy' => 'happy'),
			array('ion-happy-outline' => 'happy-outline'),
			array('ion-headphone' => 'headphone'),
			array('ion-heart' => 'heart'),
			array('ion-heart-broken' => 'heart-broken'),
			array('ion-help' => 'help'),
			array('ion-help-buoy' => 'help-buoy'),
			array('ion-help-circled' => 'help-circled'),
			array('ion-home' => 'home'),
			array('ion-icecream' => 'icecream'),
			array('ion-image' => 'image'),
			array('ion-images' => 'images'),
			array('ion-information' => 'information'),
			array('ion-information-circled' => 'information-circled'),
			array('ion-ionic' => 'ionic'),
			array('ion-ipad' => 'ipad'),
			array('ion-iphone' => 'iphone'),
			array('ion-ipod' => 'ipod'),
			array('ion-jet' => 'jet'),
			array('ion-key' => 'key'),
			array('ion-knife' => 'knife'),
			array('ion-laptop' => 'laptop'),
			array('ion-leaf' => 'leaf'),
			array('ion-levels' => 'levels'),
			array('ion-lightbulb' => 'lightbulb'),
			array('ion-link' => 'link'),
			array('ion-load-a' => 'load-a'),
			array('ion-load-b' => 'load-b'),
			array('ion-load-c' => 'load-c'),
			array('ion-load-d' => 'load-d'),
			array('ion-location' => 'location'),
			array('ion-lock-combination' => 'lock-combination'),
			array('ion-locked' => 'locked'),
			array('ion-log-in' => 'log-in'),
			array('ion-log-out' => 'log-out'),
			array('ion-loop' => 'loop'),
			array('ion-magnet' => 'magnet'),
			array('ion-male' => 'male'),
			array('ion-man' => 'man'),
			array('ion-map' => 'map'),
			array('ion-medkit' => 'medkit'),
			array('ion-merge' => 'merge'),
			array('ion-mic-a' => 'mic-a'),
			array('ion-mic-b' => 'mic-b'),
			array('ion-mic-c' => 'mic-c'),
			array('ion-minus' => 'minus'),
			array('ion-minus-circled' => 'minus-circled'),
			array('ion-minus-round' => 'minus-round'),
			array('ion-model-s' => 'model-s'),
			array('ion-monitor' => 'monitor'),
			array('ion-more' => 'more'),
			array('ion-mouse' => 'mouse'),
			array('ion-music-note' => 'music-note'),
			array('ion-navicon' => 'navicon'),
			array('ion-navicon-round' => 'navicon-round'),
			array('ion-navigate' => 'navigate'),
			array('ion-network' => 'network'),
			array('ion-no-smoking' => 'no-smoking'),
			array('ion-nuclear' => 'nuclear'),
			array('ion-outlet' => 'outlet'),
			array('ion-paintbrush' => 'paintbrush'),
			array('ion-paintbucket' => 'paintbucket'),
			array('ion-paper-airplane' => 'paper-airplane'),
			array('ion-paperclip' => 'paperclip'),
			array('ion-pause' => 'pause'),
			array('ion-person' => 'person'),
			array('ion-person-add' => 'person-add'),
			array('ion-person-stalker' => 'person-stalker'),
			array('ion-pie-graph' => 'pie-graph'),
			array('ion-pin' => 'pin'),
			array('ion-pinpoint' => 'pinpoint'),
			array('ion-pizza' => 'pizza'),
			array('ion-plane' => 'plane'),
			array('ion-planet' => 'planet'),
			array('ion-play' => 'play'),
			array('ion-playstation' => 'playstation'),
			array('ion-plus' => 'plus'),
			array('ion-plus-circled' => 'plus-circled'),
			array('ion-plus-round' => 'plus-round'),
			array('ion-podium' => 'podium'),
			array('ion-pound' => 'pound'),
			array('ion-power' => 'power'),
			array('ion-pricetag' => 'pricetag'),
			array('ion-pricetags' => 'pricetags'),
			array('ion-printer' => 'printer'),
			array('ion-pull-request' => 'pull-request'),
			array('ion-qr-scanner' => 'qr-scanner'),
			array('ion-quote' => 'quote'),
			array('ion-radio-waves' => 'radio-waves'),
			array('ion-record' => 'record'),
			array('ion-refresh' => 'refresh'),
			array('ion-reply' => 'reply'),
			array('ion-reply-all' => 'reply-all'),
			array('ion-ribbon-a' => 'ribbon-a'),
			array('ion-ribbon-b' => 'ribbon-b'),
			array('ion-sad' => 'sad'),
			array('ion-sad-outline' => 'sad-outline'),
			array('ion-scissors' => 'scissors'),
			array('ion-search' => 'search'),
			array('ion-settings' => 'settings'),
			array('ion-share' => 'share'),
			array('ion-shuffle' => 'shuffle'),
			array('ion-skip-backward' => 'skip-backward'),
			array('ion-skip-forward' => 'skip-forward'),
			array('ion-soup-can' => 'soup-can'),
			array('ion-soup-can-outline' => 'soup-can-outline'),
			array('ion-speakerphone' => 'speakerphone'),
			array('ion-speedometer' => 'speedometer'),
			array('ion-spoon' => 'spoon'),
			array('ion-star' => 'star'),
			array('ion-stats-bars' => 'stats-bars'),
			array('ion-steam' => 'steam'),
			array('ion-stop' => 'stop'),
			array('ion-thermometer' => 'thermometer'),
			array('ion-thumbsdown' => 'thumbsdown'),
			array('ion-thumbsup' => 'thumbsup'),
			array('ion-toggle' => 'toggle'),
			array('ion-toggle-filled' => 'toggle-filled'),
			array('ion-transgender' => 'transgender'),
			array('ion-trash-a' => 'trash-a'),
			array('ion-trash-b' => 'trash-b'),
			array('ion-trophy' => 'trophy'),
			array('ion-tshirt' => 'tshirt'),
			array('ion-tshirt-outline' => 'tshirt-outline'),
			array('ion-umbrella' => 'umbrella'),
			array('ion-university' => 'university'),
			array('ion-unlocked' => 'unlocked'),
			array('ion-upload' => 'upload'),
			array('ion-usb' => 'usb'),
			array('ion-videocamera' => 'videocamera'),
			array('ion-volume-high' => 'volume-high'),
			array('ion-volume-low' => 'volume-low'),
			array('ion-volume-medium' => 'volume-medium'),
			array('ion-volume-mute' => 'volume-mute'),
			array('ion-wand' => 'wand'),
			array('ion-waterdrop' => 'waterdrop'),
			array('ion-wifi' => 'wifi'),
			array('ion-wineglass' => 'wineglass'),
			array('ion-woman' => 'woman'),
			array('ion-wrench' => 'wrench'),
			array('ion-xbox' => 'xbox'),
		),
		'Social'  => array(
			array('ion-social-android' => 'android'),
			array('ion-social-android-outline' => 'android-outline'),
			array('ion-social-angular' => 'angular'),
			array('ion-social-angular-outline' => 'angular-outline'),
			array('ion-social-apple' => 'apple'),
			array('ion-social-apple-outline' => 'apple-outline'),
			array('ion-social-bitcoin' => 'bitcoin'),
			array('ion-social-bitcoin-outline' => 'bitcoin-outline'),
			array('ion-social-buffer' => 'buffer'),
			array('ion-social-buffer-outline' => 'buffer-outline'),
			array('ion-social-chrome' => 'chrome'),
			array('ion-social-chrome-outline' => 'chrome-outline'),
			array('ion-social-codepen' => 'codepen'),
			array('ion-social-codepen-outline' => 'codepen-outline'),
			array('ion-social-css3' => 'css3'),
			array('ion-social-css3-outline' => 'css3-outline'),
			array('ion-social-designernews' => 'designernews'),
			array('ion-social-designernews-outline' => 'designernews-outline'),
			array('ion-social-dribbble' => 'dribbble'),
			array('ion-social-dribbble-outline' => 'dribbble-outline'),
			array('ion-social-dropbox' => 'dropbox'),
			array('ion-social-dropbox-outline' => 'dropbox-outline'),
			array('ion-social-euro' => 'euro'),
			array('ion-social-euro-outline' => 'euro-outline'),
			array('ion-social-facebook' => 'facebook'),
			array('ion-social-facebook-outline' => 'facebook-outline'),
			array('ion-social-foursquare' => 'foursquare'),
			array('ion-social-foursquare-outline' => 'foursquare-outline'),
			array('ion-social-freebsd-devil' => 'freebsd-devil'),
			array('ion-social-github' => 'github'),
			array('ion-social-github-outline' => 'github-outline'),
			array('ion-social-google' => 'google'),
			array('ion-social-google-outline' => 'google-outline'),
			array('ion-social-googleplus' => 'googleplus'),
			array('ion-social-googleplus-outline' => 'googleplus-outline'),
			array('ion-social-hackernews' => 'hackernews'),
			array('ion-social-hackernews-outline' => 'hackernews-outline'),
			array('ion-social-html5' => 'html5'),
			array('ion-social-html5-outline' => 'html5-outline'),
			array('ion-social-instagram' => 'instagram'),
			array('ion-social-instagram-outline' => 'instagram-outline'),
			array('ion-social-javascript' => 'javascript'),
			array('ion-social-javascript-outline' => 'javascript-outline'),
			array('ion-social-linkedin' => 'linkedin'),
			array('ion-social-linkedin-outline' => 'linkedin-outline'),
			array('ion-social-markdown' => 'markdown'),
			array('ion-social-nodejs' => 'nodejs'),
			array('ion-social-octocat' => 'octocat'),
			array('ion-social-pinterest' => 'pinterest'),
			array('ion-social-pinterest-outline' => 'pinterest-outline'),
			array('ion-social-python' => 'python'),
			array('ion-social-reddit' => 'reddit'),
			array('ion-social-reddit-outline' => 'reddit-outline'),
			array('ion-social-rss' => 'rss'),
			array('ion-social-rss-outline' => 'rss-outline'),
			array('ion-social-sass' => 'sass'),
			array('ion-social-skype' => 'skype'),
			array('ion-social-skype-outline' => 'skype-outline'),
			array('ion-social-snapchat' => 'snapchat'),
			array('ion-social-snapchat-outline' => 'snapchat-outline'),
			array('ion-social-tumblr' => 'tumblr'),
			array('ion-social-tumblr-outline' => 'tumblr-outline'),
			array('ion-social-tux' => 'tux'),
			array('ion-social-twitch' => 'twitch'),
			array('ion-social-twitch-outline' => 'twitch-outline'),
			array('ion-social-twitter' => 'twitter'),
			array('ion-social-twitter-outline' => 'twitter-outline'),
			array('ion-social-usd' => 'usd'),
			array('ion-social-usd-outline' => 'usd-outline'),
			array('ion-social-vimeo' => 'vimeo'),
			array('ion-social-vimeo-outline' => 'vimeo-outline'),
			array('ion-social-whatsapp' => 'whatsapp'),
			array('ion-social-whatsapp-outline' => 'whatsapp-outline'),
			array('ion-social-windows' => 'windows'),
			array('ion-social-windows-outline' => 'windows-outline'),
			array('ion-social-wordpress' => 'wordpress'),
			array('ion-social-wordpress-outline' => 'wordpress-outline'),
			array('ion-social-yahoo' => 'yahoo'),
			array('ion-social-yahoo-outline' => 'yahoo-outline'),
			array('ion-social-yen' => 'yen'),
			array('ion-social-yen-outline' => 'yen-outline'),
			array('ion-social-youtube' => 'youtube'),
			array('ion-social-youtube-outline' => 'youtube-outline'),
		),
		'Ios'     => array(
			array('ion-ios-alarm' => 'alarm'),
			array('ion-ios-alarm-outline' => 'alarm-outline'),
			array('ion-ios-albums' => 'albums'),
			array('ion-ios-albums-outline' => 'albums-outline'),
			array('ion-ios-americanfootball' => 'americanfootball'),
			array('ion-ios-americanfootball-outline' => 'americanfootball-outline'),
			array('ion-ios-analytics' => 'analytics'),
			array('ion-ios-analytics-outline' => 'analytics-outline'),
			array('ion-ios-arrow-back' => 'arrow-back'),
			array('ion-ios-arrow-down' => 'arrow-down'),
			array('ion-ios-arrow-forward' => 'arrow-forward'),
			array('ion-ios-arrow-left' => 'arrow-left'),
			array('ion-ios-arrow-right' => 'arrow-right'),
			array('ion-ios-arrow-thin-down' => 'arrow-thin-down'),
			array('ion-ios-arrow-thin-left' => 'arrow-thin-left'),
			array('ion-ios-arrow-thin-right' => 'arrow-thin-right'),
			array('ion-ios-arrow-thin-up' => 'arrow-thin-up'),
			array('ion-ios-arrow-up' => 'arrow-up'),
			array('ion-ios-at' => 'at'),
			array('ion-ios-at-outline' => 'at-outline'),
			array('ion-ios-barcode' => 'barcode'),
			array('ion-ios-barcode-outline' => 'barcode-outline'),
			array('ion-ios-baseball' => 'baseball'),
			array('ion-ios-baseball-outline' => 'baseball-outline'),
			array('ion-ios-basketball' => 'basketball'),
			array('ion-ios-basketball-outline' => 'basketball-outline'),
			array('ion-ios-bell' => 'bell'),
			array('ion-ios-bell-outline' => 'bell-outline'),
			array('ion-ios-body' => 'body'),
			array('ion-ios-body-outline' => 'body-outline'),
			array('ion-ios-bolt' => 'bolt'),
			array('ion-ios-bolt-outline' => 'bolt-outline'),
			array('ion-ios-book' => 'book'),
			array('ion-ios-book-outline' => 'book-outline'),
			array('ion-ios-bookmarks' => 'bookmarks'),
			array('ion-ios-bookmarks-outline' => 'bookmarks-outline'),
			array('ion-ios-box' => 'box'),
			array('ion-ios-box-outline' => 'box-outline'),
			array('ion-ios-briefcase' => 'briefcase'),
			array('ion-ios-briefcase-outline' => 'briefcase-outline'),
			array('ion-ios-browsers' => 'browsers'),
			array('ion-ios-browsers-outline' => 'browsers-outline'),
			array('ion-ios-calculator' => 'calculator'),
			array('ion-ios-calculator-outline' => 'calculator-outline'),
			array('ion-ios-calendar' => 'calendar'),
			array('ion-ios-calendar-outline' => 'calendar-outline'),
			array('ion-ios-camera' => 'camera'),
			array('ion-ios-camera-outline' => 'camera-outline'),
			array('ion-ios-cart' => 'cart'),
			array('ion-ios-cart-outline' => 'cart-outline'),
			array('ion-ios-chatboxes' => 'chatboxes'),
			array('ion-ios-chatboxes-outline' => 'chatboxes-outline'),
			array('ion-ios-chatbubble' => 'chatbubble'),
			array('ion-ios-chatbubble-outline' => 'chatbubble-outline'),
			array('ion-ios-checkmark' => 'checkmark'),
			array('ion-ios-checkmark-empty' => 'checkmark-empty'),
			array('ion-ios-checkmark-outline' => 'checkmark-outline'),
			array('ion-ios-circle-filled' => 'circle-filled'),
			array('ion-ios-circle-outline' => 'circle-outline'),
			array('ion-ios-clock' => 'clock'),
			array('ion-ios-clock-outline' => 'clock-outline'),
			array('ion-ios-close' => 'close'),
			array('ion-ios-close-empty' => 'close-empty'),
			array('ion-ios-close-outline' => 'close-outline'),
			array('ion-ios-cloud' => 'cloud'),
			array('ion-ios-cloud-download' => 'cloud-download'),
			array('ion-ios-cloud-download-outline' => 'cloud-download-outline'),
			array('ion-ios-cloud-outline' => 'cloud-outline'),
			array('ion-ios-cloud-upload' => 'cloud-upload'),
			array('ion-ios-cloud-upload-outline' => 'cloud-upload-outline'),
			array('ion-ios-cloudy' => 'cloudy'),
			array('ion-ios-cloudy-night' => 'cloudy-night'),
			array('ion-ios-cloudy-night-outline' => 'cloudy-night-outline'),
			array('ion-ios-cloudy-outline' => 'cloudy-outline'),
			array('ion-ios-cog' => 'cog'),
			array('ion-ios-cog-outline' => 'cog-outline'),
			array('ion-ios-color-filter' => 'color-filter'),
			array('ion-ios-color-filter-outline' => 'color-filter-outline'),
			array('ion-ios-color-wand' => 'color-wand'),
			array('ion-ios-color-wand-outline' => 'color-wand-outline'),
			array('ion-ios-compose' => 'compose'),
			array('ion-ios-compose-outline' => 'compose-outline'),
			array('ion-ios-contact' => 'contact'),
			array('ion-ios-contact-outline' => 'contact-outline'),
			array('ion-ios-copy' => 'copy'),
			array('ion-ios-copy-outline' => 'copy-outline'),
			array('ion-ios-crop' => 'crop'),
			array('ion-ios-crop-strong' => 'crop-strong'),
			array('ion-ios-download' => 'download'),
			array('ion-ios-download-outline' => 'download-outline'),
			array('ion-ios-drag' => 'drag'),
			array('ion-ios-email' => 'email'),
			array('ion-ios-email-outline' => 'email-outline'),
			array('ion-ios-eye' => 'eye'),
			array('ion-ios-eye-outline' => 'eye-outline'),
			array('ion-ios-fastforward' => 'fastforward'),
			array('ion-ios-fastforward-outline' => 'fastforward-outline'),
			array('ion-ios-filing' => 'filing'),
			array('ion-ios-filing-outline' => 'filing-outline'),
			array('ion-ios-film' => 'film'),
			array('ion-ios-film-outline' => 'film-outline'),
			array('ion-ios-flag' => 'flag'),
			array('ion-ios-flag-outline' => 'flag-outline'),
			array('ion-ios-flame' => 'flame'),
			array('ion-ios-flame-outline' => 'flame-outline'),
			array('ion-ios-flask' => 'flask'),
			array('ion-ios-flask-outline' => 'flask-outline'),
			array('ion-ios-flower' => 'flower'),
			array('ion-ios-flower-outline' => 'flower-outline'),
			array('ion-ios-folder' => 'folder'),
			array('ion-ios-folder-outline' => 'folder-outline'),
			array('ion-ios-football' => 'football'),
			array('ion-ios-football-outline' => 'football-outline'),
			array('ion-ios-game-controller-a' => 'game-controller-a'),
			array('ion-ios-game-controller-a-outline' => 'game-controller-a-outline'),
			array('ion-ios-game-controller-b' => 'game-controller-b'),
			array('ion-ios-game-controller-b-outline' => 'game-controller-b-outline'),
			array('ion-ios-gear' => 'gear'),
			array('ion-ios-gear-outline' => 'gear-outline'),
			array('ion-ios-glasses' => 'glasses'),
			array('ion-ios-glasses-outline' => 'glasses-outline'),
			array('ion-ios-grid-view' => 'grid-view'),
			array('ion-ios-grid-view-outline' => 'grid-view-outline'),
			array('ion-ios-heart' => 'heart'),
			array('ion-ios-heart-outline' => 'heart-outline'),
			array('ion-ios-help' => 'help'),
			array('ion-ios-help-empty' => 'help-empty'),
			array('ion-ios-help-outline' => 'help-outline'),
			array('ion-ios-home' => 'home'),
			array('ion-ios-home-outline' => 'home-outline'),
			array('ion-ios-infinite' => 'infinite'),
			array('ion-ios-infinite-outline' => 'infinite-outline'),
			array('ion-ios-information' => 'information'),
			array('ion-ios-information-empty' => 'information-empty'),
			array('ion-ios-information-outline' => 'information-outline'),
			array('ion-ios-ionic-outline' => 'ionic-outline'),
			array('ion-ios-keypad' => 'keypad'),
			array('ion-ios-keypad-outline' => 'keypad-outline'),
			array('ion-ios-lightbulb' => 'lightbulb'),
			array('ion-ios-lightbulb-outline' => 'lightbulb-outline'),
			array('ion-ios-list' => 'list'),
			array('ion-ios-list-outline' => 'list-outline'),
			array('ion-ios-location' => 'location'),
			array('ion-ios-location-outline' => 'location-outline'),
			array('ion-ios-locked' => 'locked'),
			array('ion-ios-locked-outline' => 'locked-outline'),
			array('ion-ios-loop' => 'loop'),
			array('ion-ios-loop-strong' => 'loop-strong'),
			array('ion-ios-medical' => 'medical'),
			array('ion-ios-medical-outline' => 'medical-outline'),
			array('ion-ios-medkit' => 'medkit'),
			array('ion-ios-medkit-outline' => 'medkit-outline'),
			array('ion-ios-mic' => 'mic'),
			array('ion-ios-mic-off' => 'mic-off'),
			array('ion-ios-mic-outline' => 'mic-outline'),
			array('ion-ios-minus' => 'minus'),
			array('ion-ios-minus-empty' => 'minus-empty'),
			array('ion-ios-minus-outline' => 'minus-outline'),
			array('ion-ios-monitor' => 'monitor'),
			array('ion-ios-monitor-outline' => 'monitor-outline'),
			array('ion-ios-moon' => 'moon'),
			array('ion-ios-moon-outline' => 'moon-outline'),
			array('ion-ios-more' => 'more'),
			array('ion-ios-more-outline' => 'more-outline'),
			array('ion-ios-musical-note' => 'musical-note'),
			array('ion-ios-musical-notes' => 'musical-notes'),
			array('ion-ios-navigate' => 'navigate'),
			array('ion-ios-navigate-outline' => 'navigate-outline'),
			array('ion-ios-nutrition' => 'nutrition'),
			array('ion-ios-nutrition-outline' => 'nutrition-outline'),
			array('ion-ios-paper' => 'paper'),
			array('ion-ios-paper-outline' => 'paper-outline'),
			array('ion-ios-paperplane' => 'paperplane'),
			array('ion-ios-paperplane-outline' => 'paperplane-outline'),
			array('ion-ios-partlysunny' => 'partlysunny'),
			array('ion-ios-partlysunny-outline' => 'partlysunny-outline'),
			array('ion-ios-pause' => 'pause'),
			array('ion-ios-pause-outline' => 'pause-outline'),
			array('ion-ios-paw' => 'paw'),
			array('ion-ios-paw-outline' => 'paw-outline'),
			array('ion-ios-people' => 'people'),
			array('ion-ios-people-outline' => 'people-outline'),
			array('ion-ios-person' => 'person'),
			array('ion-ios-person-outline' => 'person-outline'),
			array('ion-ios-personadd' => 'personadd'),
			array('ion-ios-personadd-outline' => 'personadd-outline'),
			array('ion-ios-photos' => 'photos'),
			array('ion-ios-photos-outline' => 'photos-outline'),
			array('ion-ios-pie' => 'pie'),
			array('ion-ios-pie-outline' => 'pie-outline'),
			array('ion-ios-pint' => 'pint'),
			array('ion-ios-pint-outline' => 'pint-outline'),
			array('ion-ios-play' => 'play'),
			array('ion-ios-play-outline' => 'play-outline'),
			array('ion-ios-plus' => 'plus'),
			array('ion-ios-plus-empty' => 'plus-empty'),
			array('ion-ios-plus-outline' => 'plus-outline'),
			array('ion-ios-pricetag' => 'pricetag'),
			array('ion-ios-pricetag-outline' => 'pricetag-outline'),
			array('ion-ios-pricetags' => 'pricetags'),
			array('ion-ios-pricetags-outline' => 'pricetags-outline'),
			array('ion-ios-printer' => 'printer'),
			array('ion-ios-printer-outline' => 'printer-outline'),
			array('ion-ios-pulse' => 'pulse'),
			array('ion-ios-pulse-strong' => 'pulse-strong'),
			array('ion-ios-rainy' => 'rainy'),
			array('ion-ios-rainy-outline' => 'rainy-outline'),
			array('ion-ios-recording' => 'recording'),
			array('ion-ios-recording-outline' => 'recording-outline'),
			array('ion-ios-redo' => 'redo'),
			array('ion-ios-redo-outline' => 'redo-outline'),
			array('ion-ios-refresh' => 'refresh'),
			array('ion-ios-refresh-empty' => 'refresh-empty'),
			array('ion-ios-refresh-outline' => 'refresh-outline'),
			array('ion-ios-reload' => 'reload'),
			array('ion-ios-reverse-camera' => 'reverse-camera'),
			array('ion-ios-reverse-camera-outline' => 'reverse-camera-outline'),
			array('ion-ios-rewind' => 'rewind'),
			array('ion-ios-rewind-outline' => 'rewind-outline'),
			array('ion-ios-rose' => 'rose'),
			array('ion-ios-rose-outline' => 'rose-outline'),
			array('ion-ios-search' => 'search'),
			array('ion-ios-search-strong' => 'search-strong'),
			array('ion-ios-settings' => 'settings'),
			array('ion-ios-settings-strong' => 'settings-strong'),
			array('ion-ios-shuffle' => 'shuffle'),
			array('ion-ios-shuffle-strong' => 'shuffle-strong'),
			array('ion-ios-skipbackward' => 'skipbackward'),
			array('ion-ios-skipbackward-outline' => 'skipbackward-outline'),
			array('ion-ios-skipforward' => 'skipforward'),
			array('ion-ios-skipforward-outline' => 'skipforward-outline'),
			array('ion-ios-snowy' => 'snowy'),
			array('ion-ios-speedometer' => 'speedometer'),
			array('ion-ios-speedometer-outline' => 'speedometer-outline'),
			array('ion-ios-star' => 'star'),
			array('ion-ios-star-half' => 'star-half'),
			array('ion-ios-star-outline' => 'star-outline'),
			array('ion-ios-stopwatch' => 'stopwatch'),
			array('ion-ios-stopwatch-outline' => 'stopwatch-outline'),
			array('ion-ios-sunny' => 'sunny'),
			array('ion-ios-sunny-outline' => 'sunny-outline'),
			array('ion-ios-telephone' => 'telephone'),
			array('ion-ios-telephone-outline' => 'telephone-outline'),
			array('ion-ios-tennisball' => 'tennisball'),
			array('ion-ios-tennisball-outline' => 'tennisball-outline'),
			array('ion-ios-thunderstorm' => 'thunderstorm'),
			array('ion-ios-thunderstorm-outline' => 'thunderstorm-outline'),
			array('ion-ios-time' => 'time'),
			array('ion-ios-time-outline' => 'time-outline'),
			array('ion-ios-timer' => 'timer'),
			array('ion-ios-timer-outline' => 'timer-outline'),
			array('ion-ios-toggle' => 'toggle'),
			array('ion-ios-toggle-outline' => 'toggle-outline'),
			array('ion-ios-trash' => 'trash'),
			array('ion-ios-trash-outline' => 'trash-outline'),
			array('ion-ios-undo' => 'undo'),
			array('ion-ios-undo-outline' => 'undo-outline'),
			array('ion-ios-unlocked' => 'unlocked'),
			array('ion-ios-unlocked-outline' => 'unlocked-outline'),
			array('ion-ios-upload' => 'upload'),
			array('ion-ios-upload-outline' => 'upload-outline'),
			array('ion-ios-videocam' => 'videocam'),
			array('ion-ios-videocam-outline' => 'videocam-outline'),
			array('ion-ios-volume-high' => 'volume-high'),
			array('ion-ios-volume-low' => 'volume-low'),
			array('ion-ios-wineglass' => 'wineglass'),
			array('ion-ios-wineglass-outline' => 'wineglass-outline'),
			array('ion-ios-world' => 'world'),
			array('ion-ios-world-outline' => 'world-outline'),
		),
		'Android' => array(
			array('ion-android-add' => 'add'),
			array('ion-android-add-circle' => 'add-circle'),
			array('ion-android-alarm-clock' => 'alarm-clock'),
			array('ion-android-alert' => 'alert'),
			array('ion-android-apps' => 'apps'),
			array('ion-android-archive' => 'archive'),
			array('ion-android-arrow-back' => 'arrow-back'),
			array('ion-android-arrow-down' => 'arrow-down'),
			array('ion-android-arrow-dropdown' => 'arrow-dropdown'),
			array('ion-android-arrow-dropdown-circle' => 'arrow-dropdown-circle'),
			array('ion-android-arrow-dropleft' => 'arrow-dropleft'),
			array('ion-android-arrow-dropleft-circle' => 'arrow-dropleft-circle'),
			array('ion-android-arrow-dropright' => 'arrow-dropright'),
			array('ion-android-arrow-dropright-circle' => 'arrow-dropright-circle'),
			array('ion-android-arrow-dropup' => 'arrow-dropup'),
			array('ion-android-arrow-dropup-circle' => 'arrow-dropup-circle'),
			array('ion-android-arrow-forward' => 'arrow-forward'),
			array('ion-android-arrow-up' => 'arrow-up'),
			array('ion-android-attach' => 'attach'),
			array('ion-android-bar' => 'bar'),
			array('ion-android-bicycle' => 'bicycle'),
			array('ion-android-boat' => 'boat'),
			array('ion-android-bookmark' => 'bookmark'),
			array('ion-android-bulb' => 'bulb'),
			array('ion-android-bus' => 'bus'),
			array('ion-android-calendar' => 'calendar'),
			array('ion-android-call' => 'call'),
			array('ion-android-camera' => 'camera'),
			array('ion-android-cancel' => 'cancel'),
			array('ion-android-car' => 'car'),
			array('ion-android-cart' => 'cart'),
			array('ion-android-chat' => 'chat'),
			array('ion-android-checkbox' => 'checkbox'),
			array('ion-android-checkbox-blank' => 'checkbox-blank'),
			array('ion-android-checkbox-outline' => 'checkbox-outline'),
			array('ion-android-checkbox-outline-blank' => 'checkbox-outline-blank'),
			array('ion-android-checkmark-circle' => 'checkmark-circle'),
			array('ion-android-clipboard' => 'clipboard'),
			array('ion-android-close' => 'close'),
			array('ion-android-cloud' => 'cloud'),
			array('ion-android-cloud-circle' => 'cloud-circle'),
			array('ion-android-cloud-done' => 'cloud-done'),
			array('ion-android-cloud-outline' => 'cloud-outline'),
			array('ion-android-color-palette' => 'color-palette'),
			array('ion-android-compass' => 'compass'),
			array('ion-android-contact' => 'contact'),
			array('ion-android-contacts' => 'contacts'),
			array('ion-android-contract' => 'contract'),
			array('ion-android-create' => 'create'),
			array('ion-android-delete' => 'delete'),
			array('ion-android-desktop' => 'desktop'),
			array('ion-android-document' => 'document'),
			array('ion-android-done' => 'done'),
			array('ion-android-done-all' => 'done-all'),
			array('ion-android-download' => 'download'),
			array('ion-android-drafts' => 'drafts'),
			array('ion-android-exit' => 'exit'),
			array('ion-android-expand' => 'expand'),
			array('ion-android-favorite' => 'favorite'),
			array('ion-android-favorite-outline' => 'favorite-outline'),
			array('ion-android-film' => 'film'),
			array('ion-android-folder' => 'folder'),
			array('ion-android-folder-open' => 'folder-open'),
			array('ion-android-funnel' => 'funnel'),
			array('ion-android-globe' => 'globe'),
			array('ion-android-hand' => 'hand'),
			array('ion-android-hangout' => 'hangout'),
			array('ion-android-happy' => 'happy'),
			array('ion-android-home' => 'home'),
			array('ion-android-image' => 'image'),
			array('ion-android-laptop' => 'laptop'),
			array('ion-android-list' => 'list'),
			array('ion-android-locate' => 'locate'),
			array('ion-android-lock' => 'lock'),
			array('ion-android-mail' => 'mail'),
			array('ion-android-map' => 'map'),
			array('ion-android-menu' => 'menu'),
			array('ion-android-microphone' => 'microphone'),
			array('ion-android-microphone-off' => 'microphone-off'),
			array('ion-android-more-horizontal' => 'more-horizontal'),
			array('ion-android-more-vertical' => 'more-vertical'),
			array('ion-android-navigate' => 'navigate'),
			array('ion-android-notifications' => 'notifications'),
			array('ion-android-notifications-none' => 'notifications-none'),
			array('ion-android-notifications-off' => 'notifications-off'),
			array('ion-android-open' => 'open'),
			array('ion-android-options' => 'options'),
			array('ion-android-people' => 'people'),
			array('ion-android-person' => 'person'),
			array('ion-android-person-add' => 'person-add'),
			array('ion-android-phone-landscape' => 'phone-landscape'),
			array('ion-android-phone-portrait' => 'phone-portrait'),
			array('ion-android-pin' => 'pin'),
			array('ion-android-plane' => 'plane'),
			array('ion-android-playstore' => 'playstore'),
			array('ion-android-print' => 'print'),
			array('ion-android-radio-button-off' => 'radio-button-off'),
			array('ion-android-radio-button-on' => 'radio-button-on'),
			array('ion-android-refresh' => 'refresh'),
			array('ion-android-remove' => 'remove'),
			array('ion-android-remove-circle' => 'remove-circle'),
			array('ion-android-restaurant' => 'restaurant'),
			array('ion-android-sad' => 'sad'),
			array('ion-android-search' => 'search'),
			array('ion-android-send' => 'send'),
			array('ion-android-settings' => 'settings'),
			array('ion-android-share' => 'share'),
			array('ion-android-share-alt' => 'share-alt'),
			array('ion-android-star' => 'star'),
			array('ion-android-star-half' => 'star-half'),
			array('ion-android-star-outline' => 'star-outline'),
			array('ion-android-stopwatch' => 'stopwatch'),
			array('ion-android-subway' => 'subway'),
			array('ion-android-sunny' => 'sunny'),
			array('ion-android-sync' => 'sync'),
			array('ion-android-textsms' => 'textsms'),
			array('ion-android-time' => 'time'),
			array('ion-android-train' => 'train'),
			array('ion-android-unlock' => 'unlock'),
			array('ion-android-upload' => 'upload'),
			array('ion-android-volume-down' => 'volume-down'),
			array('ion-android-volume-mute' => 'volume-mute'),
			array('ion-android-volume-off' => 'volume-off'),
			array('ion-android-volume-up' => 'volume-up'),
			array('ion-android-walk' => 'walk'),
			array('ion-android-warning' => 'warning'),
			array('ion-android-watch' => 'watch'),
			array('ion-android-wifi' => 'wifi'),
		),
	);

	return array_merge($icons, $ionicons);
});

add_filter('vc_iconpicker-type-et_line', function ($icons) {
	$et_line = array(
		'Common' => array(

			array('et-icon-mobile' => 'et-icon-mobile'),

			array('et-icon-laptop' => 'et-icon-laptop'),

			array('et-icon-desktop' => 'et-icon-desktop'),

			array('et-icon-tablet' => 'et-icon-tablet'),

			array('et-icon-phone' => 'et-icon-phone'),

			array('et-icon-document' => 'et-icon-document'),

			array('et-icon-documents' => 'et-icon-documents'),

			array('et-icon-search' => 'et-icon-search'),

			array('et-icon-clipboard' => 'et-icon-clipboard'),

			array('et-icon-newspaper' => 'et-icon-newspaper'),

			array('et-icon-notebook' => 'et-icon-notebook'),

			array('et-icon-book-open' => 'et-icon-book-open'),

			array('et-icon-browser' => 'et-icon-browser'),

			array('et-icon-calendar' => 'et-icon-calendar'),

			array('et-icon-presentation' => 'et-icon-presentation'),

			array('et-icon-picture' => 'et-icon-picture'),

			array('et-icon-pictures' => 'et-icon-pictures'),

			array('et-icon-video' => 'et-icon-video'),

			array('et-icon-camera' => 'et-icon-camera'),

			array('et-icon-printer' => 'et-icon-printer'),

			array('et-icon-toolbox' => 'et-icon-toolbox'),

			array('et-icon-briefcase' => 'et-icon-briefcase'),

			array('et-icon-wallet' => 'et-icon-wallet'),

			array('et-icon-gift' => 'et-icon-gift'),

			array('et-icon-bargraph' => 'et-icon-bargraph'),

			array('et-icon-grid' => 'et-icon-grid'),

			array('et-icon-expand' => 'et-icon-expand'),

			array('et-icon-focus' => 'et-icon-focus'),

			array('et-icon-edit' => 'et-icon-edit'),

			array('et-icon-adjustments' => 'et-icon-adjustments'),

			array('et-icon-ribbon' => 'et-icon-ribbon'),

			array('et-icon-hourglass' => 'et-icon-hourglass'),

			array('et-icon-lock' => 'et-icon-lock'),

			array('et-icon-megaphone' => 'et-icon-megaphone'),

			array('et-icon-shield' => 'et-icon-shield'),

			array('et-icon-trophy' => 'et-icon-trophy'),

			array('et-icon-flag' => 'et-icon-flag'),

			array('et-icon-map' => 'et-icon-map'),

			array('et-icon-puzzle' => 'et-icon-puzzle'),

			array('et-icon-basket' => 'et-icon-basket'),

			array('et-icon-envelope' => 'et-icon-envelope'),

			array('et-icon-streetsign' => 'et-icon-streetsign'),

			array('et-icon-telescope' => 'et-icon-telescope'),

			array('et-icon-gears' => 'et-icon-gears'),

			array('et-icon-key' => 'et-icon-key'),

			array('et-icon-paperclip' => 'et-icon-paperclip'),

			array('et-icon-attachment' => 'et-icon-attachment'),

			array('et-icon-pricetags' => 'et-icon-pricetags'),

			array('et-icon-lightbulb' => 'et-icon-lightbulb'),

			array('et-icon-layers' => 'et-icon-layers'),

			array('et-icon-pencil' => 'et-icon-pencil'),

			array('et-icon-tools' => 'et-icon-tools'),

			array('et-icon-tools-2' => 'et-icon-tools-2'),

			array('et-icon-scissors' => 'et-icon-scissors'),

			array('et-icon-paintbrush' => 'et-icon-paintbrush'),

			array('et-icon-magnifying-glass' => 'et-icon-magnifying-glass'),

			array('et-icon-circle-compass' => 'et-icon-circle-compass'),

			array('et-icon-linegraph' => 'et-icon-linegraph'),

			array('et-icon-mic' => 'et-icon-mic'),

			array('et-icon-strategy' => 'et-icon-strategy'),

			array('et-icon-beaker' => 'et-icon-beaker'),

			array('et-icon-caution' => 'et-icon-caution'),

			array('et-icon-recycle' => 'et-icon-recycle'),

			array('et-icon-anchor' => 'et-icon-anchor'),

			array('et-icon-profile-male' => 'et-icon-profile-male'),

			array('et-icon-profile-female' => 'et-icon-profile-female'),

			array('et-icon-bike' => 'et-icon-bike'),

			array('et-icon-wine' => 'et-icon-wine'),

			array('et-icon-hotairballoon' => 'et-icon-hotairballoon'),

			array('et-icon-globe' => 'et-icon-globe'),

			array('et-icon-genius' => 'et-icon-genius'),

			array('et-icon-map-pin' => 'et-icon-map-pin'),

			array('et-icon-dial' => 'et-icon-dial'),

			array('et-icon-chat' => 'et-icon-chat'),

			array('et-icon-heart' => 'et-icon-heart'),

			array('et-icon-cloud' => 'et-icon-cloud'),

			array('et-icon-upload' => 'et-icon-upload'),

			array('et-icon-download' => 'et-icon-download'),

			array('et-icon-target' => 'et-icon-target'),

			array('et-icon-hazardous' => 'et-icon-hazardous'),

			array('et-icon-piechart' => 'et-icon-piechart'),

			array('et-icon-speedometer' => 'et-icon-speedometer'),

			array('et-icon-global' => 'et-icon-global'),

			array('et-icon-compass' => 'et-icon-compass'),

			array('et-icon-lifesaver' => 'et-icon-lifesaver'),

			array('et-icon-clock' => 'et-icon-clock'),

			array('et-icon-aperture' => 'et-icon-aperture'),

			array('et-icon-quote' => 'et-icon-quote'),

			array('et-icon-scope' => 'et-icon-scope'),

			array('et-icon-alarmclock' => 'et-icon-alarmclock'),

			array('et-icon-refresh' => 'et-icon-refresh'),

			array('et-icon-happy' => 'et-icon-happy'),

			array('et-icon-sad' => 'et-icon-sad'),

			array('et-icon-facebook' => 'et-icon-facebook'),

			array('et-icon-twitter' => 'et-icon-twitter'),

			array('et-icon-googleplus' => 'et-icon-googleplus'),

			array('et-icon-rss' => 'et-icon-rss'),

			array('et-icon-tumblr' => 'et-icon-tumblr'),

			array('et-icon-linkedin' => 'et-icon-linkedin'),

			array('et-icon-dribbble' => 'et-icon-dribbble'),
		),
	);

	return array_merge($icons, $et_line);
});

