<?php
// All possible google fonts
// List created on Feb 13, 2014
if ( ! function_exists( 'titan_get_googlefonts' ) ) {
	function titan_get_googlefonts() {
		$fonts = array(
				array( 'name' => 'ABeeZee', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Abel', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Abril Fatface', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Aclonica', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Acme', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Actor', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Adamina', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Advent Pro', 'subsets' => array('greek', 'latin-ext', 'latin'), 'variants' => array('100', '200', '300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Aguafina Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Akronim', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Aladin', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Aldrich', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Alef', 'subsets' => array('hebrew', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Alegreya', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Alegreya SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Alegreya Sans', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Alegreya Sans SC', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Alex Brush', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Alfa Slab One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Alice', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Alike', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Alike Angular', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Allan', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Allerta', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Allerta Stencil', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Allura', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Almendra', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Almendra Display', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Almendra SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Amarante', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Amaranth', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Amatic SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Amethysta', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Amiri', 'subsets' => array('arabic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Amita', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Anaheim', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Andada', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Andika', 'subsets' => array('latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Angkor', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Annie Use Your Telescope', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Anonymous Pro', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Antic', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Antic Didone', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Antic Slab', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Anton', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Arapey', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Arbutus', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Arbutus Slab', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Architects Daughter', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Archivo Black', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Archivo Narrow', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Arimo', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'hebrew', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Arizonia', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Armata', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Artifika', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Arvo', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Arya', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Asap', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Asar', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Asset', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Astloch', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Asul', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Atomic Age', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Aubrey', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Audiowide', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Autour One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Average', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Average Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Averia Gruesa Libre', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Averia Libre', 'subsets' => array('latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Averia Sans Libre', 'subsets' => array('latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Averia Serif Libre', 'subsets' => array('latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Bad Script', 'subsets' => array('cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Balthazar', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bangers', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Basic', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Battambang', 'subsets' => array('khmer'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Baumans', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bayon', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Belgrano', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Belleza', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'BenchNine', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Bentham', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Berkshire Swash', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bevan', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bigelow Rules', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bigshot One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bilbo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bilbo Swash Caps', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Biryani', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('200', '300', 'regular', '600', '700', '800', '900') ),
				array( 'name' => 'Bitter', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Black Ops One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bokor', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Bonbon', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Boogaloo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bowlby One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bowlby One SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Brawler', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bree Serif', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bubblegum Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Bubbler One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Buda', 'subsets' => array('latin'), 'variants' => array('300') ),
				array( 'name' => 'Buenard', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Butcherman', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Butterfly Kids', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cabin', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic') ),
				array( 'name' => 'Cabin Condensed', 'subsets' => array('latin'), 'variants' => array('regular', '500', '600', '700') ),
				array( 'name' => 'Cabin Sketch', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Caesar Dressing', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cagliostro', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Calligraffitti', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cambay', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Cambo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Candal', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cantarell', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Cantata One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cantora One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Capriola', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cardo', 'subsets' => array('greek', 'latin-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Carme', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Carrois Gothic', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Carrois Gothic SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Carter One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Catamaran', 'subsets' => array('latin-ext', 'tamil', 'latin'), 'variants' => array('100', '200', '300', 'regular', '500', '600', '700', '800', '900') ),
				array( 'name' => 'Caudex', 'subsets' => array('greek', 'latin-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Caveat', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Caveat Brush', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cedarville Cursive', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ceviche One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Changa One', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Chango', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Chau Philomene One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Chela One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Chelsea Market', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Chenla', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Cherry Cream Soda', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cherry Swash', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Chewy', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Chicle', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Chivo', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '900', '900italic') ),
				array( 'name' => 'Chonburi', 'subsets' => array('latin-ext', 'thai', 'vietnamese', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cinzel', 'subsets' => array('latin'), 'variants' => array('regular', '700', '900') ),
				array( 'name' => 'Cinzel Decorative', 'subsets' => array('latin'), 'variants' => array('regular', '700', '900') ),
				array( 'name' => 'Clicker Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Coda', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '800') ),
				array( 'name' => 'Coda Caption', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('800') ),
				array( 'name' => 'Codystar', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular') ),
				array( 'name' => 'Combo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Comfortaa', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Coming Soon', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Concert One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Condiment', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Content', 'subsets' => array('khmer'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Contrail One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Convergence', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cookie', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Copse', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Corben', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Courgette', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cousine', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'hebrew', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Coustard', 'subsets' => array('latin'), 'variants' => array('regular', '900') ),
				array( 'name' => 'Covered By Your Grace', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Crafty Girls', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Creepster', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Crete Round', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Crimson Text', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '600', '600italic', '700', '700italic') ),
				array( 'name' => 'Croissant One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Crushed', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cuprum', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Cutive', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Cutive Mono', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Damion', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dancing Script', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Dangrek', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Dawning of a New Day', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Days One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dekko', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Delius', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Delius Swash Caps', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Delius Unicase', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Della Respira', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Denk One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Devonshire', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dhurjati', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Didact Gothic', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Diplomata', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Diplomata SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Domine', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Donegal One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Doppio One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dorsa', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dosis', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('200', '300', 'regular', '500', '600', '700', '800') ),
				array( 'name' => 'Dr Sugiyama', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Droid Sans', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Droid Sans Mono', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Droid Serif', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Duru Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Dynalight', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'EB Garamond', 'subsets' => array('latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Eagle Lake', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Eater', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Economica', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Eczar', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '500', '600', '700', '800') ),
				array( 'name' => 'Ek Mukta', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('200', '300', 'regular', '500', '600', '700', '800') ),
				array( 'name' => 'Electrolize', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Elsie', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '900') ),
				array( 'name' => 'Elsie Swash Caps', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '900') ),
				array( 'name' => 'Emblema One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Emilys Candy', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Engagement', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Englebert', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Enriqueta', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Erica One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Esteban', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Euphoria Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ewert', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Exo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('100', '100italic', '200', '200italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Exo 2', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('100', '100italic', '200', '200italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Expletus Sans', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic') ),
				array( 'name' => 'Fanwood Text', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Fascinate', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fascinate Inline', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Faster One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fasthand', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Fauna One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Federant', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Federo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Felipa', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fenix', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Finger Paint', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fira Mono', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Fira Sans', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic') ),
				array( 'name' => 'Fjalla One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fjord One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Flamenco', 'subsets' => array('latin'), 'variants' => array('300', 'regular') ),
				array( 'name' => 'Flavors', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fondamento', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Fontdiner Swanky', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Forum', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Francois One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Freckle Face', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fredericka the Great', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fredoka One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Freehand', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Fresca', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Frijole', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fruktur', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Fugaz One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'GFS Didot', 'subsets' => array('greek'), 'variants' => array('regular') ),
				array( 'name' => 'GFS Neohellenic', 'subsets' => array('greek'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Gabriela', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gafata', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Galdeano', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Galindo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gentium Basic', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Gentium Book Basic', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Geo', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Geostar', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Geostar Fill', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Germania One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gidugu', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gilda Display', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Give You Glory', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Glass Antiqua', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Glegoo', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Gloria Hallelujah', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Goblin One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gochi Hand', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gorditas', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Goudy Bookletter 1911', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Graduate', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Grand Hotel', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gravitas One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Great Vibes', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Griffy', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gruppo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Gudea', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Gurajada', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Habibi', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Halant', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Hammersmith One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Hanalei', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Hanalei Fill', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Handlee', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Hanuman', 'subsets' => array('khmer'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Happy Monkey', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Headland One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Henny Penny', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Herr Von Muellerhoff', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Hind', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Hind Siliguri', 'subsets' => array('latin-ext', 'bengali', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Hind Vadodara', 'subsets' => array('latin-ext', 'gujarati', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Holtwood One SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Homemade Apple', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Homenaje', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'IM Fell DW Pica', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'IM Fell DW Pica SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'IM Fell Double Pica', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'IM Fell Double Pica SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'IM Fell English', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'IM Fell English SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'IM Fell French Canon', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'IM Fell French Canon SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'IM Fell Great Primer', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'IM Fell Great Primer SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Iceberg', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Iceland', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Imprima', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Inconsolata', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Inder', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Indie Flower', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Inika', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Inknut Antiqua', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700', '800', '900') ),
				array( 'name' => 'Irish Grover', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Istok Web', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Italiana', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Italianno', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Itim', 'subsets' => array('latin-ext', 'thai', 'vietnamese', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jacques Francois', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jacques Francois Shadow', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jaldi', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Jim Nightshade', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jockey One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jolly Lodger', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Josefin Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '600', '600italic', '700', '700italic') ),
				array( 'name' => 'Josefin Slab', 'subsets' => array('latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '600', '600italic', '700', '700italic') ),
				array( 'name' => 'Joti One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Judson', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Julee', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Julius Sans One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Junge', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Jura', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('300', 'regular', '500', '600') ),
				array( 'name' => 'Just Another Hand', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Just Me Again Down Here', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kadwa', 'subsets' => array('devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Kalam', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Kameron', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Kanit', 'subsets' => array('latin-ext', 'thai', 'vietnamese', 'latin'), 'variants' => array('100', '100italic', '200', '200italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Kantumruy', 'subsets' => array('khmer'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Karla', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Karma', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Kaushan Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kavoon', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kdam Thmor', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Keania One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kelly Slab', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kenia', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Khand', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Khmer', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Khula', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '600', '700', '800') ),
				array( 'name' => 'Kite One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Knewave', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kotta One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Koulen', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Kranky', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kreon', 'subsets' => array('latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Kristi', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Krona One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Kurale', 'subsets' => array('latin-ext', 'cyrillic', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'La Belle Aurore', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Laila', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Lakki Reddy', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lancelot', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lateef', 'subsets' => array('arabic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lato', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'League Script', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Leckerli One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ledger', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lekton', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Lemon', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Libre Baskerville', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Life Savers', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Lilita One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lily Script One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Limelight', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Linden Hill', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Lobster', 'subsets' => array('latin-ext', 'vietnamese', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lobster Two', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Londrina Outline', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Londrina Shadow', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Londrina Sketch', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Londrina Solid', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lora', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Love Ya Like A Sister', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Loved by the King', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lovers Quarrel', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Luckiest Guy', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Lusitana', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Lustria', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Macondo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Macondo Swash Caps', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Magra', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Maiden Orange', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mako', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mallanna', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mandali', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Marcellus', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Marcellus SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Marck Script', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Margarine', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Marko One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Marmelad', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Martel', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('200', '300', 'regular', '600', '700', '800', '900') ),
				array( 'name' => 'Martel Sans', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('200', '300', 'regular', '600', '700', '800', '900') ),
				array( 'name' => 'Marvel', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Mate', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Mate SC', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Maven Pro', 'subsets' => array('latin'), 'variants' => array('regular', '500', '700', '900') ),
				array( 'name' => 'McLaren', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Meddon', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'MedievalSharp', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Medula One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Megrim', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Meie Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Merienda', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Merienda One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Merriweather', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Merriweather Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic', '800', '800italic') ),
				array( 'name' => 'Metal', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Metal Mania', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Metamorphous', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Metrophobic', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Michroma', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Milonga', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Miltonian', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Miltonian Tattoo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Miniver', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Miss Fajardose', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Modak', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Modern Antiqua', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Molengo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Molle', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('italic') ),
				array( 'name' => 'Monda', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Monofett', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Monoton', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Monsieur La Doulaise', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Montaga', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Montez', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Montserrat', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Montserrat Alternates', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Montserrat Subrayada', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Moul', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Moulpali', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Mountains of Christmas', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Mouse Memoirs', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mr Bedfort', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mr Dafoe', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mr De Haviland', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mrs Saint Delafield', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Mrs Sheppards', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Muli', 'subsets' => array('latin'), 'variants' => array('300', '300italic', 'regular', 'italic') ),
				array( 'name' => 'Mystery Quest', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'NTR', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Neucha', 'subsets' => array('cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Neuton', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('200', '300', 'regular', 'italic', '700', '800') ),
				array( 'name' => 'New Rocker', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'News Cycle', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Niconne', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nixie One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nobile', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Nokora', 'subsets' => array('khmer'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Norican', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nosifer', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nothing You Could Do', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Noticia Text', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Noto Sans', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'devanagari', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Noto Serif', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Nova Cut', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Flat', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Mono', 'subsets' => array('greek', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Oval', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Round', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Script', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Slim', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nova Square', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Numans', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Nunito', 'subsets' => array('latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Odor Mean Chey', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Offside', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Old Standard TT', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Oldenburg', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Oleo Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Oleo Script Swash Caps', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Open Sans', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '600', '600italic', '700', '700italic', '800', '800italic') ),
				array( 'name' => 'Open Sans Condensed', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('300', '300italic', '700') ),
				array( 'name' => 'Oranienbaum', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Orbitron', 'subsets' => array('latin'), 'variants' => array('regular', '500', '700', '900') ),
				array( 'name' => 'Oregano', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Orienta', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Original Surfer', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Oswald', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Over the Rainbow', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Overlock', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Overlock SC', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ovo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Oxygen', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Oxygen Mono', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'PT Mono', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'PT Sans', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'PT Sans Caption', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'PT Sans Narrow', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'PT Serif', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'PT Serif Caption', 'subsets' => array('latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Pacifico', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Palanquin', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('100', '200', '300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Palanquin Dark', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '500', '600', '700') ),
				array( 'name' => 'Paprika', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Parisienne', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Passero One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Passion One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700', '900') ),
				array( 'name' => 'Pathway Gothic One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Patrick Hand', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Patrick Hand SC', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Patua One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Paytone One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Peddana', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Peralta', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Permanent Marker', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Petit Formal Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Petrona', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Philosopher', 'subsets' => array('cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Piedra', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Pinyon Script', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Pirata One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Plaster', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Play', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Playball', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Playfair Display', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Playfair Display SC', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Podkova', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Poiret One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Poller One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Poly', 'subsets' => array('latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Pompiere', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Pontano Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Poppins', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Port Lligat Sans', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Port Lligat Slab', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Pragati Narrow', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Prata', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Preahvihear', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Press Start 2P', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Princess Sofia', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Prociono', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Prosto One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Puritan', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Purple Purse', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Quando', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Quantico', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Quattrocento', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Quattrocento Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Questrial', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Quicksand', 'subsets' => array('latin'), 'variants' => array('300', 'regular', '700') ),
				array( 'name' => 'Quintessential', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Qwigley', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Racing Sans One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Radley', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Rajdhani', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Raleway', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('100', '100italic', '200', '200italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '600', '600italic', '700', '700italic', '800', '800italic', '900', '900italic') ),
				array( 'name' => 'Raleway Dots', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ramabhadra', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ramaraja', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rambla', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Rammetto One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ranchers', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rancho', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ranga', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Rationale', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ravi Prakash', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Redressed', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Reenie Beanie', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Revalia', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rhodium Libre', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ribeye', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ribeye Marrow', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Righteous', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Risque', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Roboto', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Roboto Condensed', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Roboto Mono', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('100', '100italic', '300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic') ),
				array( 'name' => 'Roboto Slab', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('100', '300', 'regular', '700') ),
				array( 'name' => 'Rochester', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rock Salt', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rokkitt', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Romanesco', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ropa Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Rosario', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Rosarivo', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Rouge Script', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rozha One', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rubik', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Rubik Mono One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rubik One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ruda', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700', '900') ),
				array( 'name' => 'Rufina', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Ruge Boogie', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ruluko', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rum Raisin', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ruslan Display', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Russo One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ruthie', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Rye', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sacramento', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sahitya', 'subsets' => array('devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Sail', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Salsa', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sanchez', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Sancreek', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sansita One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sarala', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Sarina', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sarpanch', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '500', '600', '700', '800', '900') ),
				array( 'name' => 'Satisfy', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Scada', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Scheherazade', 'subsets' => array('arabic', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Schoolbell', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Seaweed Script', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sevillana', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Seymour One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Shadows Into Light', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Shadows Into Light Two', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Shanti', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Share', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Share Tech', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Share Tech Mono', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Shojumaru', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Short Stack', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Siemreap', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Sigmar One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Signika', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular', '600', '700') ),
				array( 'name' => 'Signika Negative', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular', '600', '700') ),
				array( 'name' => 'Simonetta', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic', '900', '900italic') ),
				array( 'name' => 'Sintony', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Sirin Stencil', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Six Caps', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Skranji', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Slabo 13px', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Slabo 27px', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Slackey', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Smokum', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Smythe', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sniglet', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '800') ),
				array( 'name' => 'Snippet', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Snowburst One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sofadi One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sofia', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sonsie One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sorts Mill Goudy', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', 'italic') ),
				array( 'name' => 'Source Code Pro', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('200', '300', 'regular', '500', '600', '700', '900') ),
				array( 'name' => 'Source Sans Pro', 'subsets' => array('latin-ext', 'vietnamese', 'latin'), 'variants' => array('200', '200italic', '300', '300italic', 'regular', 'italic', '600', '600italic', '700', '700italic', '900', '900italic') ),
				array( 'name' => 'Source Serif Pro', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular', '600', '700') ),
				array( 'name' => 'Special Elite', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Spicy Rice', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Spinnaker', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Spirax', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Squada One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sree Krushnadevaraya', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Stalemate', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Stalinist One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Stardos Stencil', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Stint Ultra Condensed', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Stint Ultra Expanded', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Stoke', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('300', 'regular') ),
				array( 'name' => 'Strait', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sue Ellen Francisco', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sumana', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Sunshiney', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Supermercado One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Sura', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Suranna', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Suravaram', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Suwannaphum', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Swanky and Moo Moo', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Syncopate', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Tangerine', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Taprom', 'subsets' => array('khmer'), 'variants' => array('regular') ),
				array( 'name' => 'Tauri', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Teko', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('300', 'regular', '500', '600', '700') ),
				array( 'name' => 'Telex', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Tenali Ramakrishna', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Tenor Sans', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Text Me One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'The Girl Next Door', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Tienne', 'subsets' => array('latin'), 'variants' => array('regular', '700', '900') ),
				array( 'name' => 'Tillana', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '500', '600', '700', '800') ),
				array( 'name' => 'Timmana', 'subsets' => array('telugu', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Tinos', 'subsets' => array('greek', 'latin-ext', 'vietnamese', 'cyrillic', 'hebrew', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Titan One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Titillium Web', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('200', '200italic', '300', '300italic', 'regular', 'italic', '600', '600italic', '700', '700italic', '900') ),
				array( 'name' => 'Trade Winds', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Trocchi', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Trochut', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700') ),
				array( 'name' => 'Trykker', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Tulpen One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ubuntu', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('300', '300italic', 'regular', 'italic', '500', '500italic', '700', '700italic') ),
				array( 'name' => 'Ubuntu Condensed', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Ubuntu Mono', 'subsets' => array('greek', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek-ext', 'latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Ultra', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Uncial Antiqua', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Underdog', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Unica One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'UnifrakturCook', 'subsets' => array('latin'), 'variants' => array('700') ),
				array( 'name' => 'UnifrakturMaguntia', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Unkempt', 'subsets' => array('latin'), 'variants' => array('regular', '700') ),
				array( 'name' => 'Unlock', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Unna', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'VT323', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Vampiro One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Varela', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Varela Round', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Vast Shadow', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Vesper Libre', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('regular', '500', '700', '900') ),
				array( 'name' => 'Vibur', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Vidaloka', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Viga', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Voces', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Volkhov', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Vollkorn', 'subsets' => array('latin'), 'variants' => array('regular', 'italic', '700', '700italic') ),
				array( 'name' => 'Voltaire', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Waiting for the Sunrise', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Wallpoet', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Walter Turncoat', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Warnes', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Wellfleet', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Wendy One', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Wire One', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Work Sans', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('100', '200', '300', 'regular', '500', '600', '700', '800', '900') ),
				array( 'name' => 'Yanone Kaffeesatz', 'subsets' => array('latin-ext', 'latin'), 'variants' => array('200', '300', 'regular', '700') ),
				array( 'name' => 'Yantramanav', 'subsets' => array('latin-ext', 'devanagari', 'latin'), 'variants' => array('100', '300', 'regular', '500', '700', '900') ),
				array( 'name' => 'Yellowtail', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Yeseva One', 'subsets' => array('latin-ext', 'cyrillic', 'latin'), 'variants' => array('regular') ),
				array( 'name' => 'Yesteryear', 'subsets' => array('latin'), 'variants' => array('regular') ),
				array( 'name' => 'Zeyada', 'subsets' => array('latin'), 'variants' => array('regular') ),
		);
		return $fonts;
	}
}